# 25. Convert a dictonary to Pandas dataframe

In [1]:
import pandas as pd
import numpy as np
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, np.nan, 35, 40],
    'score': [90, 85, np.nan, 88]
}
df = pd.DataFrame(data)
df.to_csv(f'data/output_pandas.csv', index=True)

<br><br>

# 26. Write Python code to add a new column to a pandas DataFrame with all values set to zero.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(f"data/SOCR-HeightWeight.csv")
df.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

### Add new column

In [4]:
df['BMI'] = df['Weight(Pounds)'] / (df['Height(Inches)'] ** 2) * 703
df.head()

   Index  Height(Inches)  Weight(Pounds)        BMI
0      1        65.78331        112.9925  18.355808
1      2        71.51521        136.4873  18.760773
2      3        69.39874        153.0269  22.336747
3      4        68.21660        142.3354  21.502458
4      5        67.78781        144.2971  22.075458

In [5]:
df.to_csv(f'data/Height-Weight-BMI.csv', index=True)

<br><br>

#  27. Write Python code to delete a column named age from a dataset.

In [6]:
df = pd.read_csv("data/Height-Weight-BMI.csv")
df.columns

Index(['Unnamed: 0', 'Index', 'Height(Inches)', 'Weight(Pounds)', 'BMI'], dtype='object')

In [7]:
df=df.drop(columns='BMI')
# For more than one column
# df = df.drop(columns=['BMI', 'Height(Inches)'])
df.columns

Index(['Unnamed: 0', 'Index', 'Height(Inches)', 'Weight(Pounds)'], dtype='object')

<br><br>

# 28. Write Python code to remove rows with missing values (NaN) from a dataset

### Example DataFrame with NaN values
```
import pandas as pd
import numpy as np
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, np.nan, 35, 40],
    'score': [90, 85, np.nan, 88]
}
df = pd.DataFrame(data)
```

In [8]:
df=pd.read_csv(f"data/NAN-HeightWeightBMI.csv")
df.head()

   Index  Height(Inches)  Weight(Pounds)        BMI
0      1        65.78331        112.9925  18.355808
1      2        71.51521        136.4873        NaN
2      3        69.39874        153.0269  22.336747
3      4        68.21660             NaN  21.502458
4      5        67.78781        144.2971  22.075458

In [9]:
# Remove rows with any NaN values
df = df.dropna()
df

       Index  Height(Inches)  Weight(Pounds)        BMI
0          1        65.78331        112.9925  18.355808
2          3        69.39874        153.0269  22.336747
4          5        67.78781        144.2971  22.075458
6          7        69.80204        141.4947  20.415465
8          9        67.90265        112.3723  17.133305
...      ...             ...             ...        ...
24995  24996        69.50215        118.0312  17.177330
24996  24997        64.54826        120.1932  20.279916
24997  24998        64.69855        118.2655  19.862061
24998  24999        67.52918        132.2682  20.390497
24999  25000        68.87761        124.8742  18.504268

[24991 rows x 4 columns]

<br><br>

#  29. Write Python code to fill missing values with the mean of the column.

In [10]:
df=pd.read_csv(f"data/NAN-HeightWeightBMI.csv")
df.head()

   Index  Height(Inches)  Weight(Pounds)        BMI
0      1        65.78331        112.9925  18.355808
1      2        71.51521        136.4873        NaN
2      3        69.39874        153.0269  22.336747
3      4        68.21660             NaN  21.502458
4      5        67.78781        144.2971  22.075458

In [11]:
df.columns

Index(['Index', 'Height(Inches)', 'Weight(Pounds)', 'BMI'], dtype='object')

In [12]:
# Fill missing values in numeric columns with the column mean
df['Height(Inches)'] = df['Height(Inches)'].fillna(df['Height(Inches)'].mean())
df['Weight(Pounds)'] = df['Weight(Pounds)'].fillna(df['Weight(Pounds)'].mean())
df['BMI'] = df['BMI'].fillna(df['BMI'].mean())
df.head()

   Index  Height(Inches)  Weight(Pounds)        BMI
0      1        65.78331      112.992500  18.355808
1      2        71.51521      136.487300  19.319585
2      3        69.39874      153.026900  22.336747
3      4        68.21660      127.079268  21.502458
4      5        67.78781      144.297100  22.075458

<br><br>

# 30. How to split your dataset into training and testing sets (80-20)

In [13]:
df=pd.read_csv(f"data/500_Person_Gender_Height_Weight_Index.csv")
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

Index :  
0 - Extremely Weak  
1 - Weak  
2 - Normal  
3 - Overweight  
4 - Obesity  
5 - Extreme Obesity

In [14]:
df.columns

Index(['Gender', 'Height', 'Weight', 'Index'], dtype='object')

In [15]:
from sklearn.model_selection import train_test_split

# Spliting into features (X) and target (y) as NumPy arrays
X = df.drop(columns='Index').values   # Features as NumPy array (by .values we converted in mp array)
y = df['Index'].values                 # Target as NumPy array

# Spliting into train/test (example 80-20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train:\n", X_train[:10])
print("y_train:\n", y_train[:10])

X_train:
 [['Male' 161 89]
 ['Male' 179 127]
 ['Male' 172 139]
 ['Male' 153 104]
 ['Male' 165 68]
 ['Male' 172 92]
 ['Male' 182 108]
 ['Male' 179 130]
 ['Male' 142 71]
 ['Female' 158 153]]
y_train:
 [4 4 5 5 2 4 4 5 4 5]

<br><br>